[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["cd server && npm install"]

[phases.build]
cmds = ["echo 'Skipping frontend build for backend deployment'"]

[start]
cmd = "cd server && node simple-index.js" 