[build]
builder = "nixpacks"

[deploy]
startCommand = "node server/simple-index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production" 