[build]
builder = "NIXPACKS"
buildCommand = "sh -lc 'cd server && (npm ci || npm install --no-audit --no-fund)'"

[deploy]
startCommand = "cd server && node simple-index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 